
name: Push git tag on pyproject.toml version bump

on:
  push:
    branches:
      - master

jobs:
  tag:
    name: Create Tag on version bump
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install & Build Poetry
        run: pip install poetry

      - name: Get project version via poetry
        id: get_version
        run: echo "VERSION=$(poetry version -s)" >> $GITHUB_OUTPUT

      - name: Create and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag v${{ steps.get_version.outputs.VERSION }}
          git push -f origin v${{ steps.get_version.outputs.VERSION }}
